name: Branch Naming Convention Check

on:
  create:
    branches:
      - '**'

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ ! $BRANCH_NAME =~ ^(feature|hotfix)/[a-z0-9-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention"
            echo "Allowed patterns: feature/*, hotfix/*"
            exit 1
          fi